# Generated by Django 4.2 on 2024-04-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructor', models.CharField(max_length=50)),
                ('duration_minutes', models.IntegerField()),
                ('price_bdt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ols_app.course')),
            ],
        ),
    ]
