# Generated by Django 4.2 on 2024-04-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ols_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='course',
            new_name='course_id',
        ),
    ]
